In [1]:
import numpy as np

In [2]:
class Logistic_Neuron:

  def __init__(self, n_inputs, learning_rate=0.1):
    self.w = - 1 + 2 * np.random.rand(n_inputs)
    self.b = - 1 + 2 * np.random.rand()
    self.eta = learning_rate

  def predict_prob(self, X):
      Z = np.dot(self.w, X) + self.b
      Y_est = 1 / (1 + np.exp(-Z))
      return Y_est
    
  def predict_class(self, X):
      Z = np.dot(self.w, X) + self.b
      Y_est = 1 / (1 + np.exp(-Z))
      return 1 * (Y_est > 0.5)

  def fit(self, X, Y, epochs = 50): # Full-batch gradient descent
    p = X.shape[1]
    for _ in range(epochs):
          Y_est = self.predict_prob(X)    # Binary cross entropy
          self.w += (self.eta / p) * np.dot((Y - Y_est), X.T).ravel()
          self.b += (self.eta / p) * np.sum(Y - Y_est)

In [3]:
X_and = np.array([[0, 0, 1, 1],
                  [0, 1, 0, 1]])

Y_and = np.array([0, 0, 0, 1])


X_or =  np.array([[0, 0, 1, 1],
                  [0, 1, 0, 1]])

Y_or =  np.array([0, 1, 1, 1])


X_xor =  np.array([[0, 0, 1, 1],
                   [0, 1, 0, 1]])

Y_xor =  np.array([0, 1, 1, 0])

In [4]:
neuron = Logistic_Neuron(2, 1)
print("Logistic neuron before training")
print(neuron.predict_prob(X_and))
print(neuron.predict_class(X_and))

neuron.fit(X_and, Y_and, epochs=600)

print("Logistic neuron after training")
print(neuron.predict_prob(X_and))
print(neuron.predict_class(X_and))

Logistic neuron before training
[0.66973583 0.64162494 0.69864829 0.67179233]
[1 1 1 1]
Logistic neuron after training
[5.91130183e-05 3.34889893e-02 3.34890324e-02 9.53070823e-01]
[0 0 0 1]
