In [1]:
import numpy as np

In [2]:
def linear(z, derivative=False):
    a = z
    if(derivative):
        da = np.ones(z.shape)
        return a, da
    
    return a

def sigmoid(z, derivative=False): # logistic
    a = 1 / (1 + np.exp(-z))
    if(derivative):
        da = a * (1 - a)
        return a, da
    
    return a

def tanh(z, derivative=False):
    a = np.tanh(z)
    if(derivative):
        da = (1 + a) * (1 - a)
        return a, da
    
    return a

def relu(z, derivative=False):
    a = z * (z >= 0)
    if(derivative):
        da = np.array((z >= 0), dtype=np.float64)
        return a, da
    
    return a

In [3]:
class OLN: # One Layer Network

    def __init__(self, n_inputs, n_outputs, activation_fnc):
        self.w = -1 + 2 * np.random.rand(n_outputs, n_inputs)
        self.b = -1 + 2 * np.random.rand(n_outputs, 1)
        self.f = activation_fnc

    def predict(self, X, derivative=False): # Propagation
        Z = np.dot(self.w, X) + self.b
        return self.f(Z, derivative = derivative)
    
    def fit(self, X, Y, epochs=200, lr=0.1):
        p = X.shape[1] # columnas

        for _ in range(epochs):

            Z = np.dot(self.w, X) + self.b
            Y_est, dY = self.predict(Z, derivative=True)
            # Mean Squared Error (MSE)
            local_grad = (Y - Y_est) * dY
            self.w += (lr / p) * np.dot(local_grad, X.T)
            self.b += (lr / p) * np.sum(local_grad, axis=1).reshape(-1, 1)

In [4]:
X_xor =  np.array([[0, 0, 1, 1],
                   [0, 1, 0, 1]])

Y_xor =  np.array([0, 1, 1, 0])

one_layer_network = OLN(2, 2, sigmoid)
one_layer_network.fit(X_xor, Y_xor)

print(one_layer_network.predict(X_xor))
print((0.5 <= one_layer_network.predict(X_xor)) * np.ones(X_xor.shape[1]))

[[0.47950283 0.47917528 0.59543044 0.59511425]
 [0.46014605 0.56870716 0.57522922 0.67689787]]
[[0. 0. 1. 1.]
 [0. 1. 1. 1.]]
